[package]
name = "kvs"
version = "0.1.0"
edition = "2021"
authors = ["Burak Sekili <buraksekili@gmail.com>"]
description = "A key-value store"

[dependencies]
assert_cmd = "0.11.0"
clap = { version = "4.5.7", features = ["cargo"] }
predicates = "1.0.0"
